set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX mipsel-none-elf-)
find_program(BINUTILS_PATH ${TOOLCHAIN_PREFIX}gcc NO_CACHE)

if(NOT BINUTILS_PATH)
  message(FATAL_ERROR "Arm gcc toolchain not found!")
endif()

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_AR ${TOOLCHAIN_PREFIX}gcc-ar)
set(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}gcc-ranlib)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size)

set(CPU_FLAGS "-mips32 -ffixed-k0 -ffixed-k1 -G0 -O0 -g -gdwarf-4 -EL -mhard-float -fno-delayed-branch")

set(CMAKE_C_FLAGS_INIT "-Wall -Wextra -ffunction-sections -fdata-sections ${CPU_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT ${CMAKE_C_FLAGS_INIT})
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--gc-sections")

execute_process(COMMAND ${CMAKE_C_COMPILER} -print-sysroot
  OUTPUT_VARIABLE ARM_GCC_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE)

set(CMAKE_SYSROOT ${ARM_GCC_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

unset(CMAKE_OSX_SYSROOT CACHE)
unset(CMAKE_OSX_ARCHITECTURES CACHE)
unset(CMAKE_OSX_DEPLOYMENT_TARGET CACHE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
